### ISSUE TITLE
Como foi definido o modelo?

### ISSUE THREAD

**Issue by ghost** [joaoabcoelho/ModeloCartoletas#1]
Olá @joaoabcoelho, achei muito interessante a inicativa proposta para um modelo de valorização dos jogadores ao longo das rodadas. Gostaria de saber qual foi a abordagem utilizada para estimar os coeficientes apontados no ModeloCartoleta.

Agradeço desde já!

**Comment by joaoabcoelho** [comment]
Oi @PVitorino, o modelo foi construído um pouco por tentativa e erro. Comecei olhando quais variáveis faziam sentido pra tentar ajustar os dados com regressão linear. Notei que apenas com preço e pontos você ajusta perfeitamente a primeira rodada. Depois vi que a segunda rodada funciona apenas adicionando a última pontuação. E por fim vi que usando essas três variáveis mais a média de pontos conseguia ajustar praticamente qualquer rodada. Mas tinham exceções pra jogadores que não jogaram a última rodada. Então fiz o ajuste separado pra eles. E aos poucos fui investigando padrões nos coeficientes que permitiram generalizar o modelo pra múltiplas rodadas.

Ainda há espaço pra investigar e generalizar mais o modelo. Além disso, eu sei que falta uma correção pra inflação que eu não implementei. Mas tudo indica que o modelo real do Cartola é algo linear de alguma forma.

**Comment by joaoabcoelho** [comment]
O modelo foi atualizado com o que parece ser basicamente o sistema exato de valorização do CartolaFC. Então essa questão está resolvida.
